name: V2 Rebuild latest docs

on:
  workflow_dispatch:

jobs:
  changelog:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable_publish_changelog.yml

  release-docs:
    needs: changelog
    permissions:
      contents: write
      pages: write
    uses: ./.github/workflows/reusable_publish_docs.yml
    with:
      version: v2
      alias: alpha
